#!/usr/bin/env python3
"""Prepare the existing gateway for operator-assisted, browser-first enrollment.

No public route is enabled here. This never chooses or receives the user's real
password; an initial random password is generated by Authelia and discarded.
"""
import argparse
import copy
import datetime
import importlib.util
import json
import os
from pathlib import Path
import subprocess


spec = importlib.util.spec_from_file_location("owner_setup", Path(__file__).with_name("owner-setup.py"))
owner = importlib.util.module_from_spec(spec)
spec.loader.exec_module(owner)


def browser_config(config):
    result = copy.deepcopy(config)
    backend = result["authentication_backend"]
    backend["password_reset"] = {"disable": False}
    backend["password_change"] = {"disable": False}
    backend["file"]["path"] = "/data/users.yml"
    backend["file"]["watch"] = True
    result["password_policy"] = {"standard": {"enabled": True, "min_length": 16, "max_length": 128}}
    return result


def mounts_are_safe(inspection):
    mounts = {mount["Destination"]: mount["RW"] for mount in inspection["Mounts"]}
    return (inspection["HostConfig"]["ReadonlyRootfs"] is True
            and mounts.get("/config") is False
            and mounts.get("/run/secrets") is False
            and mounts.get("/data") is True)


def main():
    import yaml
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, default=Path("/opt/hapi-gateway"))
    parser.add_argument("--username", default="owner")
    args = parser.parse_args()
    if os.geteuid() != 0 or not owner.username_valid(args.username):
        parser.error("Root privileges and a valid username are required.")
    directory = args.directory.resolve(strict=True)
    active = directory / "authelia" / "configuration.yml"
    original = active.read_bytes()
    config = yaml.safe_load(original)
    destination = directory / "authelia-data" / "users.yml"
    if config["authentication_backend"]["file"]["path"] != "/config/users.yml" or destination.exists():
        raise RuntimeError("The gateway was already migrated or has unexpected user data. No changes made.")
    source = directory / "authelia" / "users.yml"
    if not owner.bootstrap_only(owner.load_users(source)):
        raise RuntimeError("An account already exists. Refusing to replace the user's credentials.")
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = directory / ("browser-enrollment-backup-" + stamp)
    backup.mkdir(mode=0o700)
    owner.atomic_write(backup / "configuration.yml", original, 0, 0)
    owner.atomic_write(backup / "users.yml", source.read_bytes(), 0, 0)
    generated = subprocess.run(
        ["docker", "exec", owner.CONTAINER, "authelia", "crypto", "hash", "generate",
         "argon2", "--random", "--random.length", "72", "--memory", "65536",
         "--iterations", "3", "--parallelism", "4"],
        check=True, capture_output=True,
    )
    digest = owner.parse_digest(generated.stdout)
    del generated  # Never log or persist the generated plaintext password.
    owner.atomic_write(destination, owner.render_owner(args.username, digest).encode())
    replacement = yaml.safe_dump(browser_config(config), sort_keys=False).encode()
    candidate = active.with_name("configuration.browser.yml")
    owner.atomic_write(candidate, replacement)
    validation = subprocess.run(
        ["docker", "exec", owner.CONTAINER, "authelia", "validate-config", "--config",
         "/config/configuration.browser.yml"], capture_output=True,
    )
    if validation.returncode != 0:
        destination.rename(backup / "unused-users.yml")
        raise RuntimeError("Candidate validation failed. Live configuration was not changed.")
    if active.read_bytes() != original:
        destination.rename(backup / "unused-users.yml")
        raise RuntimeError("Live configuration changed concurrently. No live configuration was overwritten.")
    try:
        owner.atomic_write(active, replacement)
        owner.restart_and_check()
        inspection = json.loads(subprocess.check_output(["docker", "inspect", owner.CONTAINER]))[0]
        if not mounts_are_safe(inspection):
            raise RuntimeError("Unexpected writable configuration, secrets, or root filesystem.")
        # BusyBox test -w only checks permission bits on some bind mounts; it
        # can report writable even when the mount is enforced read-only.
        subprocess.run(
            ["docker", "exec", owner.CONTAINER, "sh", "-c",
             "test -w /data/users.yml && : >> /data/users.yml"],
            check=True, capture_output=True,
        )
    except BaseException:
        owner.atomic_write(active, original)
        owner.restart_and_check()
        destination.rename(backup / "unused-users.yml")
        raise
    print(json.dumps({"username": args.username, "healthy": True,
                      "password_changes": True, "public_hapi_enabled": False,
                      "backup": str(backup)}))


if __name__ == "__main__":
    main()
